# Generated by Django 5.0 on 2023-12-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrative',
            name='model_name',
            field=models.CharField(blank=True, max_length=130, null=True, verbose_name='Nome do modelo que foi afetado'),
        ),
    ]
