# Generated by Django 5.0 on 2023-12-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_card_grades', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='grade_level',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nivel da nota'),
        ),
    ]
