# Generated by Django 5.0 on 2023-12-15 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_card_grades', '0003_reportcard_grade_level'),
        ('school_subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='school_subject.subject', verbose_name='Matéria'),
        ),
    ]
