# Generated by Django 5.0 on 2023-12-16 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_year', '0001_initial'),
        ('user', '0002_alter_student_school_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.student')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_year.schoolyear')),
            ],
            options={
                'verbose_name': 'student_school_year',
                'verbose_name_plural': 'students_school_year',
                'db_table': 'tb_student_school_year',
            },
        ),
    ]
