# Generated by Django 5.0 on 2023-12-08 22:25

import user.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.managers.CustomUserManager()),
            ],
        ),
    ]
