# Generated by Django 5.0 on 2023-12-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(max_length=255, verbose_name='Tipe de regra criada')),
                ('rule_description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('rule_action', models.CharField(max_length=255, verbose_name='Ação realizada')),
            ],
            options={
                'verbose_name': 'rules',
                'verbose_name_plural': 'rules',
                'db_table': 'tb_rule',
            },
        ),
    ]
