# Generated by Django 5.0 on 2023-12-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(verbose_name='dia')),
                ('month', models.CharField(max_length=30, verbose_name='mês')),
                ('year', models.IntegerField(verbose_name='ano')),
                ('title', models.CharField(max_length=30, verbose_name='titulo do evento')),
                ('description', models.CharField(blank=True, max_length=30, null=True, verbose_name='descrição do evento')),
                ('item_type', models.CharField(choices=[('public', 'Publico'), ('private', 'Privado'), ('for_students', 'Para estudantes'), ('for_admin', 'Para administradores'), ('for_teacher', 'Para professores')], default='private', max_length=30, verbose_name='tipo do evento')),
                ('user_type', models.CharField(blank=True, max_length=30, null=True, verbose_name='Tipo de usuário que poderá ver esse evento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'scheduler',
                'verbose_name_plural': 'schedulers',
                'db_table': 'tb_scheduler',
            },
        ),
    ]
