# Generated by Django 5.0 on 2023-12-12 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduler',
            old_name='user_type',
            new_name='destinated_to',
        ),
    ]
