# Generated by Django 5.0 on 2023-12-12 21:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_rename_user_type_scheduler_destinated_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduler',
            name='destinated_to',
        ),
        migrations.AddField(
            model_name='scheduler',
            name='destinated_to',
            field=models.ManyToManyField(blank=True, related_name='destinated_to', to=settings.AUTH_USER_MODEL, verbose_name='destinated_to'),
        ),
    ]
