# Generated by Django 5.0 on 2023-12-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_remove_scheduler_destinated_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduler',
            name='item_type',
        ),
        migrations.AddField(
            model_name='scheduler',
            name='visibility',
            field=models.CharField(choices=[('public', 'Publico'), ('private', 'Privado'), ('for_students', 'Para estudantes'), ('for_teacher', 'Para professores')], default='private', max_length=30, verbose_name='quem pode ver o evento'),
        ),
    ]
