# Generated by Django 5.0 on 2023-12-12 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_alter_scheduler_destinated_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduler',
            name='destinated_to',
        ),
    ]
