# Generated by Django 5.0 on 2023-12-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_remove_scheduler_destinated_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='visibility',
            field=models.CharField(choices=[('public', 'Publico'), ('private', 'Somente eu'), ('for_students', 'Para estudantes'), ('for_teacher', 'Para professores')], default='private', max_length=30, verbose_name='quem pode ver o evento'),
        ),
    ]
