# Generated by Django 5.0 on 2023-12-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_alter_scheduler_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='visibility',
            field=models.CharField(choices=[('public', 'Publico'), ('private', 'Somente eu')], default='private', max_length=30, verbose_name='quem pode ver o evento'),
        ),
    ]
