# Generated by Django 5.0 on 2023-12-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('1a', 'Primeiro Ano'), ('2a', 'Segundo Ano'), ('3a', 'Terceiro Ano'), ('4a', 'Quarto Ano'), ('5a', 'Quinto Ano'), ('6a', 'Sexto Ano'), ('7a', 'Sétimo Ano'), ('8a', 'Oitavo Ano'), ('9a', 'Nono Ano'), ('1c', 'Primeiro Colegial'), ('2c', 'Segundo Colegial'), ('3c', 'Terceiro Colegial')], max_length=255, verbose_name='Ano escolar')),
            ],
            options={
                'verbose_name': 'school_year',
                'verbose_name_plural': 'school_years',
                'db_table': 'tb_school_year',
            },
        ),
    ]
